language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      compiler: gcc
      env: ENV_QTC_SOURCE="$TRAVIS_BUILD_DIR/build/downloads/qt-creator-opensource-src-3.6.0" ENV_QTC_BUILD="$TRAVIS_BUILD_DIR/build/downloads/qtcbuild/3.6.0/lib/qtcreator/" ENV_QTC_VERSION="3.6.0" ENV_QTC_MV="6" ENV_QMAKE_PARAMS="-spec linux-g++"
    - os: osx
      compiler: clang
      env: ENV_QTC_SOURCE="$TRAVIS_BUILD_DIR/build/downloads/qt-creator-opensource-src-3.6.0" ENV_QTC_BUILD="$TRAVIS_BUILD_DIR/build/downloads/qtcbuild/3.6.0/" ENV_QTC_VERSION="3.6.0" ENV_QTC_MV="6" ENV_QMAKE_PARAMS=""

env:
  global:
    - VERSION=1.0

before_install:
  - build/before_install.sh

install:
  - build/install.sh

before_script:
  - git submodule update --init

script:
  - build/script.sh
  - find "$TRAVIS_BUILD_DIR/build/plugins"

addons:
  artifacts:
    paths:
      - ./build/plugins

before_deploy:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then "$TRAVIS_BUILD_DIR/build/fix_mac.sh" $(find $TRAVIS_BUILD_DIR/build/plugins/ -name '*.dylib') ; fi
  - python "$TRAVIS_BUILD_DIR/build/generate_bintray.py" "$TRAVIS_BUILD_DIR"
  - cd "$TRAVIS_BUILD_DIR/build" && zip -r output "./plugins" && cd -

deploy:
  provider: bintray
  file: "$TRAVIS_BUILD_DIR/.bintray.json"
  user: "groterik"
  key:
    secure: "PA9xLwP/57X26aB/72j7s96TLImRHkUnYl+hXQwEgArdzz6m2UBjWj5KWdshTm/DofliaV+Giw8pD9j9vl9G3oOaT5jWPiLmScJrlEQBVJ+YN/POojj8WTJQ75WSRgRMp/jU+Y1iYttIn1Xv0G9RGzJZ/AGPHP14u6vHE3dkU5E="

