language: cpp
compiler:
  - gcc

env:
  - ENV_QTC_SOURCE="$TRAVIS_BUILD_DIR/qt-creator-opensource-src-3.4.2" ENV_QTC_BUILD="/opt/qt55/lib/x86_64-linux-gnu/qtcreator/" ENV_QTC_VERSION="3.4.2" ENV_QTC_MV="4"
  - ENV_QTC_SOURCE="$TRAVIS_BUILD_DIR/qt-creator-3.5.0-beta1" ENV_QTC_BUILD="$TRAVIS_BUILD_DIR/qtc_build/3.5.0-beta1/lib/qtcreator/" ENV_QTC_VERSION="3.5.0" ENV_QTC_MV="5"


before_install:
# Qt 5.5.0 and QtC 3.4.2
  - sudo add-apt-repository -y ppa:beineri/opt-qt55
# GCC 4.8
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
# QtC sources
  - wget "http://download.qt-project.org/official_releases/qtcreator/3.4/3.4.2/qt-creator-opensource-src-3.4.2.tar.gz"
  - tar xzf qt-creator-opensource-src-3.4.2.tar.gz
# Latest tagged QtC sources and binaries
  - wget "https://github.com/qtproject/qt-creator/archive/v3.5.0-beta1.tar.gz"
  - tar xzf v3.5.0-beta1.tar.gz
  - wget "http://download.qt.io/snapshots/qtcreator/3.5.0-beta1/latest/installer_source/qtcreator_linux-g++-Rhel6.6-x64.7z"
  - sudo apt-get install p7zip
  - 7zr x -o./qtc_build/3.5.0-beta1/ qtcreator_linux-g++-Rhel6.6-x64.7z

install:
  - sudo apt-get install qt55creator
  - sudo apt-get install -qq gcc-4.8 g++-4.8 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90 

before_script:
  - git submodule update --init

script:
  - . /opt/qt55/bin/qt55-env.sh
  - mkdir -p build && cd build
  - export PLUGIN_OUT_PATH="$(pwd)/plugins/${ENV_QTC_VERSION}/"
  - mkdir -p "${PLUGIN_OUT_PATH}" 
  - qmake ../dlangeditor.pro -r -spec linux-g++ CONFIG+=release QTC_SOURCE="${ENV_QTC_SOURCE}" QTC_BUILD="${ENV_QTC_BUILD}" OUTPUT_PATH="${PLUGIN_OUT_PATH}" SET_VERSION_MINOR="${ENV_QTC_MV}"
  - make
  - find "$TRAVIS_BUILD_DIR/build/plugins"

addons:
  artifacts:
    paths:
      - ./build/plugins
