#ifndef DLANGEDITOR_GLOBAL_H
#define DLANGEDITOR_GLOBAL_H

#include <QtGlobal>

#if defined(DLANGEDITOR_LIBRARY)
#  define DLANGEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLANGEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLANGEDITOR_GLOBAL_H

